// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3932.RobotBuildBeta.subsystems;

import org.usfirst.frc3932.RobotBuildBeta.RobotMap;
import org.usfirst.frc3932.RobotBuildBeta.commands.*;
import edu.wpi.first.wpilibj.*;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Jaguars extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    SpeedController speedController1 = RobotMap.jaguarsSpeedController1;
    SpeedController speedController2 = RobotMap.jaguarsSpeedController2;
    SpeedController speedController3 = RobotMap.jaguarsSpeedController3;
    SpeedController speedController4 = RobotMap.jaguarsSpeedController4;
    SpeedController speedController5 = RobotMap.jaguarsSpeedController5;
    SpeedController speedController6 = RobotMap.jaguarsSpeedController6;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

